In [5]:
import numpy as np

In [51]:
array=np.array([1,2,3,4,5])

In [53]:
array

array([1, 2, 3, 4, 5])

In [55]:
array_2d=np.array([range(5),range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [41]:
print(array_2d.shape)
print(array_2d.size)
print(array_2d.dtype)
print(array_2d.ndim)

(2, 5)
10
int64
2


# Numpy Array creation functions

In [26]:
newarray=np.array(["This","is","numpy"])

In [28]:
newarray.dtype

dtype('<U5')

In [30]:
np.ones(10,dtype='int').T

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
np.zeros(100,'int').reshape(10,10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [38]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Numpy random number generation

In [72]:
rng=np.random.default_rng(2022)

In [76]:
rng.random(10)

array([0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701])

In [80]:
rng.integers(1,10,100)

array([2, 2, 6, 1, 8, 3, 3, 6, 2, 8, 3, 2, 7, 5, 4, 5, 9, 1, 6, 9, 4, 6,
       7, 9, 2, 2, 9, 9, 2, 5, 7, 6, 5, 4, 4, 7, 3, 6, 4, 8, 5, 1, 8, 6,
       8, 8, 9, 7, 4, 8, 1, 7, 3, 5, 5, 4, 1, 7, 7, 9, 7, 3, 6, 7, 6, 6,
       7, 6, 6, 7, 9, 4, 7, 8, 8, 6, 9, 1, 6, 6, 3, 6, 3, 1, 1, 1, 1, 5,
       5, 5, 5, 1, 6, 9, 5, 9, 5, 8, 4, 4])

In [86]:
rng.normal(5,1,10)

array([3.61115204, 5.3072852 , 6.11340639, 5.98128573, 4.49869887,
       4.63560117, 7.10955   , 4.42935682, 4.26895327, 4.4879761 ])

# Numpy indexing and slicing

In [93]:
new_array=np.arange(12)
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
new_array[5]

5

In [107]:
new_array[1:5]

array([1, 2, 3, 4])

In [105]:
new_2Darray=new_array.reshape(3,4)
new_2Darray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
new_2Darray[2,2]

10

In [115]:
new_2Darray[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
new_2Darray[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

# Array operations

In [9]:
rng=np.random.default_rng(2000)

inventory=rng.random(20).reshape(4,5)

inventory

array([[0.57513632, 0.65642461, 0.0270377 , 0.50655723, 0.64716848],
       [0.26905058, 0.96145813, 0.41011444, 0.53526499, 0.062028  ],
       [0.1053834 , 0.54319365, 0.24362626, 0.74231498, 0.00225371],
       [0.3672471 , 0.36697658, 0.06369904, 0.11757953, 0.77782075]])

In [13]:
inventory*10

array([[5.75136319, 6.56424609, 0.27037704, 5.06557229, 6.47168476],
       [2.69050583, 9.61458133, 4.10114436, 5.3526499 , 0.62028002],
       [1.05383401, 5.43193648, 2.43626262, 7.42314979, 0.02253709],
       [3.67247099, 3.66976584, 0.6369904 , 1.17579528, 7.77820746]])

In [15]:
inventory+10

array([[10.57513632, 10.65642461, 10.0270377 , 10.50655723, 10.64716848],
       [10.26905058, 10.96145813, 10.41011444, 10.53526499, 10.062028  ],
       [10.1053834 , 10.54319365, 10.24362626, 10.74231498, 10.00225371],
       [10.3672471 , 10.36697658, 10.06369904, 10.11757953, 10.77782075]])

In [19]:
inventory.sum()

7.98033547566461

In [21]:
inventory[0,:]*inventory[1,:]

array([0.15474076, 0.63112478, 0.01108855, 0.27114235, 0.04014257])

# Array filtering and numpy 'where'

In [27]:
my_array=np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
my_array%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [29]:
my_array[my_array%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
new_array=np.array(['even','odd']*10).reshape(20)
new_array

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [37]:
my_array[new_array=='even']

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
my_array[new_array!='even']=0
my_array

array([ 0,  0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,
        0, 18,  0])

In [61]:
mask=(my_array%2==0) & (my_array!=0)
my_array[mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
np.where(mask,'even',np.where(my_array==0,my_array,'odd'))

array(['0', '0', 'even', '0', 'even', '0', 'even', '0', 'even', '0',
       'even', '0', 'even', '0', 'even', '0', 'even', '0', 'even', '0'],
      dtype='<U21')

# Array aggregation
### Check out many more functions in the docs

In [6]:
import numpy as np

In [12]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array.sum()

45

In [22]:
array.mean()

4.5

In [26]:
array.max()

9

In [30]:
array.min()

0

In [37]:
np.median(array)

4.5

In [43]:
new_array=np.zeros(10)
new_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.unique(new_array)

array([0.])

In [53]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [57]:
array=np.arange(10).reshape(5,2)
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
array.sum(axis=0)

array([20, 25])

In [65]:
array.sum(axis=1)

array([ 1,  5,  9, 13, 17])

# Array sorting

In [69]:
rng=np.random.default_rng(2022)

In [79]:
new_array=(rng.random(20)*100).round(2)
new_array

array([ 4.51, 51.28, 47.7 , 48.6 , 90.79, 51.86, 54.3 , 48.37,  8.34,
       45.12, 16.59,  0.4 , 29.45, 55.68, 86.62, 20.94, 52.1 , 50.37,
        3.61, 89.57])

In [81]:
np.sort(new_array)
# for in place sorting array_name.sort()

array([ 0.4 ,  3.61,  4.51,  8.34, 16.59, 20.94, 29.45, 45.12, 47.7 ,
       48.37, 48.6 , 50.37, 51.28, 51.86, 52.1 , 54.3 , 55.68, 86.62,
       89.57, 90.79])

In [99]:
new_array=new_array.reshape(10,2)

In [101]:
new_array.sort(axis=1)
new_array

array([[ 0.4 ,  3.61],
       [ 4.51,  8.34],
       [16.59, 20.94],
       [29.45, 45.12],
       [47.7 , 48.37],
       [48.6 , 50.37],
       [51.28, 51.86],
       [52.1 , 54.3 ],
       [55.68, 86.62],
       [89.57, 90.79]])